//! Diagnostic catalog generator.
//!
//! Reads the pinned TypeScript `diagnosticMessages.json` and renders
//! `crates/bamts-compiler/src/generated/diagnostic_messages.rs`.

use std::{
    collections::BTreeMap,
    fmt::{self, Write as _},
    fs, io,
    path::Path,
};

#[derive(Debug)]
pub enum CatalogError {
    Io(io::Error),
    Json(serde_json::Error),
    Mismatch { path: String },
}

impl From<io::Error> for CatalogError {
    fn from(err: io::Error) -> Self {
        Self::Io(err)
    }
}

impl From<serde_json::Error> for CatalogError {
    fn from(err: serde_json::Error) -> Self {
        Self::Json(err)
    }
}

impl fmt::Display for CatalogError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(err) => write!(f, "I/O error: {err}"),
            Self::Json(err) => write!(f, "JSON error: {err}"),
            Self::Mismatch { path } => write!(f, "generated file does not match: {path}"),
        }
    }
}

impl std::error::Error for CatalogError {}

#[derive(Debug, serde::Deserialize, Clone)]
struct RawEntry {
    category: String,
    code: u32,
}

const BOILERPLATE: &str = r###"
//! Generated by `crates/bamts-verification/src/diagnostic_catalog.rs`.
//! Source: `__SOURCE__`.
//! Do not hand-edit this file.
//!
//! This module is a stable, deterministic table of the diagnostic messages
//! in the TypeScript 7.0.2 authority. Every code and template is unique,
//! the table is sorted by code, and placeholders are checked at format time.
//! in the TypeScript 7.0.2 authority. Every code and template is unique,
//! the table is sorted by code, and placeholders are checked at format time.

use crate::diagnostic::{DiagnosticCode, DiagnosticSeverity};

/// TypeScript diagnostic category.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum TsCategory {
    /// The diagnostic prevents the program from compiling.
    Error,
    /// The diagnostic is non-fatal.
    Warning,
    /// The compiler suggests an optional improvement.
    Suggestion,
    /// The diagnostic is informational only.
    Message,
}

impl TsCategory {
    /// Maps the TypeScript category to the compiler's `DiagnosticSeverity`.
    #[must_use]
    pub const fn to_diagnostic_severity(self) -> DiagnosticSeverity {
        match self {
            Self::Error => DiagnosticSeverity::Error,
            // Suggestions and messages are rendered as non-fatal warnings.
            Self::Warning | Self::Suggestion | Self::Message => DiagnosticSeverity::Warning,
        }
    }
}

/// Failure while instantiating a diagnostic template.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FormatError {
    /// The number of arguments does not match the template.
    ArityMismatch { expected: usize, got: usize },
    /// A placeholder index was not within the expected range.
    BadPlaceholder { index: usize, max: usize },
}

impl std::fmt::Display for FormatError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArityMismatch { expected, got } => {
                write!(f, "expected {expected} arguments, got {got}")
            }
            Self::BadPlaceholder { index, max } => {
                write!(f, "placeholder index {index} out of range (max {max})")
            }
        }
    }
}

impl std::error::Error for FormatError {}

/// Strongly-typed substitution list for a diagnostic template.
///
/// The const generic `N` is the number of supplied arguments. This is checked
/// against the template's placeholder count at format time.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Args<'a, const N: usize>([&'a str; N]);

impl<'a, const N: usize> Args<'a, N> {
    /// Wraps the argument array.
    #[must_use]
    pub const fn new(args: [&'a str; N]) -> Self {
        Self(args)
    }
}

/// One generated diagnostic message with its code, category, and template.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DiagnosticMessage {
    code: u32,
    bamts_code: &'static str,
    ts_code: &'static str,
    category: TsCategory,
    template: &'static str,
    arity: u8,
}

impl DiagnosticMessage {
    /// The numeric diagnostic code.
    #[must_use]
    pub const fn code(&self) -> u32 {
        self.code
    }

    /// The BAMTS code string (the numeric code).
    #[must_use]
    pub const fn bamts_code(&self) -> &'static str {
        self.bamts_code
    }

    /// The canonical TypeScript `TSxxxx` label.
    #[must_use]
    pub const fn ts_code(&self) -> &'static str {
        self.ts_code
    }

    /// The diagnostic category.
    #[must_use]
    pub const fn category(&self) -> TsCategory {
        self.category
    }

    /// The message template, possibly containing `{0}`-style placeholders.
    #[must_use]
    pub const fn template(&self) -> &'static str {
        self.template
    }

    /// The number of arguments required by the template.
    #[must_use]
    pub const fn arity(&self) -> u8 {
        self.arity
    }

    /// The stable `DiagnosticCode` identity.
    #[must_use]
    pub const fn diagnostic_code(&self) -> DiagnosticCode {
        DiagnosticCode::new(self.bamts_code)
    }

    /// Renders the template with the supplied checked arguments.
    pub fn format<'a, const N: usize>(&self, args: Args<'a, N>) -> Result<String, FormatError> {
        if N != self.arity as usize {
            return Err(FormatError::ArityMismatch {
                expected: self.arity as usize,
                got: N,
            });
        }
        let mut out = String::new();
        let mut chars = self.template.chars().peekable();
        while let Some(ch) = chars.next() {
            if ch == '{' {
                let mut digits = String::new();
                while let Some(&next) = chars.peek() {
                    if next.is_ascii_digit() {
                        digits.push(next);
                        chars.next();
                    } else {
                        break;
                    }
                }
                if !digits.is_empty() && chars.peek() == Some(&'}') {
                    chars.next();
                    let index = digits.parse::<usize>().unwrap();
                    if index >= N {
                        return Err(FormatError::BadPlaceholder {
                            index,
                            max: N.saturating_sub(1),
                        });
                    }
                    out.push_str(args.0[index]);
                } else {
                    out.push(ch);
                    out.push_str(&digits);
                }
            } else {
                out.push(ch);
            }
        }
        Ok(out)
    }
}

/// Number of catalog entries.
pub const CATALOG_LEN: usize = __CATALOG_LEN__;

/// Stable, sorted, unique catalog of TypeScript diagnostic messages.
#[rustfmt::skip]
pub static CATALOG: [DiagnosticMessage; CATALOG_LEN] = [
__CATALOG__
];

/// Looks up a message by its numeric code.
#[must_use]
pub fn by_u32(code: u32) -> Option<&'static DiagnosticMessage> {
    CATALOG
        .as_slice()
        .binary_search_by(|message| message.code.cmp(&code))
        .ok()
        .map(|index| &CATALOG[index])
}

/// Looks up a message by its BAMTS code string.
#[must_use]
pub fn by_bamts_code(code: &str) -> Option<&'static DiagnosticMessage> {
    code.parse::<u32>().ok().and_then(by_u32)
}

/// Looks up a message by its TypeScript `TSxxxx` label.
#[must_use]
pub fn by_ts_code(ts_code: &str) -> Option<&'static DiagnosticMessage> {
    ts_code
        .strip_prefix("TS")?
        .parse::<u32>()
        .ok()
        .and_then(by_u32)
}

/// Looks up a message by a `DiagnosticCode`.
#[must_use]
pub fn by_diagnostic_code(code: DiagnosticCode) -> Option<&'static DiagnosticMessage> {
    by_bamts_code(code.as_str())
}

/// Returns the whole catalog for deterministic iteration.
#[must_use]
pub fn all() -> &'static [DiagnosticMessage] {
    &CATALOG
}

/// Renders a BAMTS code as its `TSxxxx` label when it is a numeric TS code.
#[must_use]
pub fn ts_code_for(code: &str) -> String {
    if !code.is_empty() && code.chars().all(|ch| ch.is_ascii_digit()) {
        format!("TS{code}")
    } else {
        code.to_owned()
    }
}

/// Returns the precomputed TS label for a known catalog entry.
#[must_use]
pub fn ts_code_for_diagnostic(code: DiagnosticCode) -> Option<&'static str> {
    by_diagnostic_code(code).map(|message| message.ts_code())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diagnostic::{DiagnosticCode, DiagnosticSeverity};

    #[test]
    fn catalog_is_sorted_and_unique() {
        for window in CATALOG.windows(2) {
            assert!(
                window[0].code < window[1].code,
                "catalog must be sorted by unique codes"
            );
            assert!(
                window[0].template != window[1].template,
                "duplicate template at codes {} and {}",
                window[0].code,
                window[1].code
            );
        }
    }

    #[test]
    fn lookup_roundtrip() {
        let message = by_ts_code("TS1002").expect("TS1002 must exist");
        assert_eq!(message.code(), 1002);
        assert_eq!(message.category(), TsCategory::Error);
        assert_eq!(message.template(), "Unterminated string literal.");
        assert_eq!(by_u32(1002), Some(message));
        assert_eq!(by_bamts_code("1002"), Some(message));
        assert_eq!(
            by_diagnostic_code(DiagnosticCode::new("1002")),
            Some(message)
        );
        let five_digit = by_u32(17000).expect("TS17000 must exist");
        assert_eq!(by_bamts_code("17000"), Some(five_digit));
        assert_eq!(by_ts_code("TS17000"), Some(five_digit));
    }

    #[test]
    fn ts_code_mapping() {
        assert_eq!(ts_code_for("1002"), "TS1002");
        assert_eq!(ts_code_for("BAMTS-C001"), "BAMTS-C001");
        assert_eq!(ts_code_for(""), "");
        assert_eq!(
            ts_code_for_diagnostic(DiagnosticCode::new("1002")),
            Some("TS1002")
        );
        assert_eq!(
            ts_code_for_diagnostic(DiagnosticCode::new("BAMTS-C001")),
            None
        );
        for message in CATALOG {
            assert_eq!(message.bamts_code(), message.code().to_string());
            assert_eq!(message.ts_code(), format!("TS{}", message.code()));
        }
    }

    #[test]
    fn substitution_checks_arity_and_renders() {
        let message = by_u32(1005).expect("code 1005 must exist");
        assert_eq!(message.arity(), 1);
        assert_eq!(
            message.format(Args::new(["x"])),
            Ok("'x' expected.".to_owned())
        );
        let empty: [&str; 0] = [];
        assert!(matches!(
            message.format(Args::new(empty)),
            Err(FormatError::ArityMismatch {
                expected: 1,
                got: 0
            })
        ));
        let two: [&str; 2] = ["a", "b"];
        assert!(matches!(
            message.format(Args::new(two)),
            Err(FormatError::ArityMismatch {
                expected: 1,
                got: 2
            })
        ));
    }

    #[test]
    fn category_to_severity() {
        assert_eq!(
            TsCategory::Error.to_diagnostic_severity(),
            DiagnosticSeverity::Error
        );
        assert_eq!(
            TsCategory::Warning.to_diagnostic_severity(),
            DiagnosticSeverity::Warning
        );
        assert_eq!(
            TsCategory::Suggestion.to_diagnostic_severity(),
            DiagnosticSeverity::Warning
        );
        assert_eq!(
            TsCategory::Message.to_diagnostic_severity(),
            DiagnosticSeverity::Warning
        );
    }

    #[test]
    fn all_placeholders_are_in_range() {
        for message in CATALOG.iter() {
            let expected = message.arity() as usize;
            let mut indices = Vec::new();
            let mut chars = message.template().chars().peekable();
            while let Some(ch) = chars.next() {
                if ch == '{' {
                    let mut digits = String::new();
                    while let Some(&next) = chars.peek() {
                        if next.is_ascii_digit() {
                            digits.push(next);
                            chars.next();
                        } else {
                            break;
                        }
                    }
                    if !digits.is_empty() && chars.peek() == Some(&'}') {
                        indices.push(digits.parse::<usize>().unwrap());
                    }
                }
            }
            for index in indices {
                assert!(
                    index < expected,
                    "template for {} has placeholder {} but arity is {}",
                    message.ts_code(),
                    index,
                    expected
                );
            }
        }
    }
}"###;

fn category_to_rust(category: &str) -> &'static str {
    match category {
        "Error" => "TsCategory::Error",
        "Warning" => "TsCategory::Warning",
        "Suggestion" => "TsCategory::Suggestion",
        "Message" => "TsCategory::Message",
        _ => "TsCategory::Message",
    }
}

fn arity(template: &str) -> u8 {
    let mut max = None::<usize>;
    let mut chars = template.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch == '{' {
            let mut digits = String::new();
            while let Some(&next) = chars.peek() {
                if next.is_ascii_digit() {
                    digits.push(next);
                    chars.next();
                } else {
                    break;
                }
            }
            if !digits.is_empty() && chars.peek() == Some(&'}') {
                let index = digits.parse::<usize>().unwrap();
                max = Some(max.map_or(index, |m| m.max(index)));
            }
        }
    }
    (max.map_or(0, |m| m + 1)) as u8
}

fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        let o = c as u32;
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ if o < 0x20 || o == 0x7f => out.push_str(&format!("\\u{{{:x}}}", o)),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}
fn render_catalog(entries: &[(u32, &str, &RawEntry)]) -> String {
    let mut out = String::new();
    for (code, template, entry) in entries {
        let _ = writeln!(out, "    DiagnosticMessage {{");
        let _ = writeln!(out, "        code: {code},");
        let _ = writeln!(out, "        bamts_code: \"{code}\",");
        let _ = writeln!(out, "        ts_code: \"TS{code}\",");
        let _ = writeln!(
            out,
            "        category: {cat},",
            cat = category_to_rust(&entry.category)
        );
        let _ = writeln!(
            out,
            "        template: {tpl},",
            tpl = escape_rust_string(template)
        );
        let _ = writeln!(out, "        arity: {arity},", arity = arity(template));
        let _ = writeln!(out, "    }},");
    }
    out
}

/// Parses the pinned JSON diagnostic catalog and renders the Rust module.
pub fn generate(json_path: &Path, source_label: &str) -> Result<String, CatalogError> {
    let text = fs::read_to_string(json_path)?;
    let raw: BTreeMap<String, RawEntry> = serde_json::from_str(&text)?;
    let mut entries: Vec<_> = raw
        .iter()
        .map(|(template, entry)| (entry.code, template.as_str(), entry))
        .collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(b.1)));

    let catalog = render_catalog(&entries);
    let mut out = BOILERPLATE.trim_start_matches('\n').to_string();
    out = out.replace("__SOURCE__", source_label);
    out = out.replace("__CATALOG_LEN__", &entries.len().to_string());
    out = out.replace("__CATALOG__", &catalog);
    out.push('\n');
    Ok(out)
}

/// Verifies that `generated_path` is the current rendering of `json_path`.
pub fn check(
    json_path: &Path,
    source_label: &str,
    generated_path: &Path,
) -> Result<(), CatalogError> {
    let rendered = generate(json_path, source_label)?;
    let on_disk = fs::read_to_string(generated_path)?;
    if rendered != on_disk {
        Err(CatalogError::Mismatch {
            path: generated_path.to_string_lossy().into_owned(),
        })
    } else {
        Ok(())
    }
}

/// Convenience: renders and writes the generated file.
pub fn write_generated(
    json_path: &Path,
    source_label: &str,
    generated_path: &Path,
) -> Result<(), CatalogError> {
    let rendered = generate(json_path, source_label)?;
    if let Some(parent) = generated_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(generated_path, rendered)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::path::PathBuf;

    fn fixture() -> Vec<u8> {
        br#"{"First {0} error.":{"category":"Error","code":9000},"Second.":{"category":"Warning","code":9001}}"#.to_vec()
    }

    #[test]
    fn fixture_generate_and_check() {
        let dir =
            std::env::temp_dir().join(format!("bamts_catalog_fixture_{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let json = dir.join("diagnosticMessages.json");
        let generated = dir.join("diagnostic_messages.rs");
        fs::write(&json, fixture()).unwrap();
        let label = json.to_string_lossy().into_owned();
        write_generated(&json, &label, &generated).unwrap();
        assert!(check(&json, &label, &generated).is_ok());
        let mut f = fs::OpenOptions::new()
            .append(true)
            .open(&generated)
            .unwrap();
        writeln!(f, "// drift").unwrap();
        assert!(check(&json, &label, &generated).is_err());
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn fixture_output_shape() {
        let dir = std::env::temp_dir().join(format!("bamts_catalog_shape_{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let json = dir.join("diagnosticMessages.json");
        fs::write(&json, fixture()).unwrap();
        let label = json.to_string_lossy().into_owned();
        let output = generate(&json, &label).unwrap();
        assert!(output.contains("code: 9000,"));
        assert!(output.contains("code: 9001,"));
        assert!(output.contains(r#"template: "First {0} error.","#));
        assert!(output.contains("arity: 1,"));
        assert!(output.contains("arity: 0,"));
        assert!(output.contains("pub const CATALOG_LEN: usize = 2;"));
        assert!(output.contains("TsCategory::Error"));
        assert!(output.contains("TsCategory::Warning"));
        let pos0 = output.find("code: 9000,").unwrap();
        let pos1 = output.find("code: 9001,").unwrap();
        assert!(pos0 < pos1, "catalog must be sorted by code");
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn fixture_escape_quotes_and_backslash() {
        let dir = std::env::temp_dir().join(format!("bamts_catalog_escape_{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let json = dir.join("diagnosticMessages.json");
        fs::write(
            &json,
            r#"{"Bad \"quote\" and \\ backslash.":{"category":"Error","code":9002}}"#.as_bytes(),
        )
        .unwrap();
        let label = json.to_string_lossy().into_owned();
        let output = generate(&json, &label).unwrap();
        assert!(output.contains(r#"template: "Bad \"quote\" and \\ backslash.","#));
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn regression_matches_checked_in() {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        if !manifest.ends_with("bamts-verification") {
            return;
        }
        let root = manifest
            .parent()
            .and_then(|p| p.parent())
            .expect("repo root");
        let source_label =
            "target/authority/typescript-7.0.2-tests/src/compiler/diagnosticMessages.json";
        let json = root.join(source_label);
        let generated = root.join("crates/bamts-compiler/src/generated/diagnostic_messages.rs");
        assert!(json.exists(), "pinned JSON missing: {:?}", json);
        assert!(
            generated.exists(),
            "generated file missing: {:?}",
            generated
        );
        check(&json, source_label, &generated)
            .expect("checked-in artifact must match pinned source");
    }
}
