[package]
name = "bamts-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
description = "Code generation (JIT/AOT) backend for BamTS"

[dependencies]
bamts-bytecode = { path = "../bamts-bytecode", version = "0.1.0" }
bamts-native = { path = "../bamts-native", version = "0.1.0", optional = true, features = ["jit-entry"] }
cranelift-codegen = { version = "=0.134.2", default-features = false, features = ["std", "unwind", "all-native-arch"] }
cranelift-frontend = "=0.134.2"
cranelift-module = "=0.134.2"
cranelift-object = { version = "=0.134.2", optional = true }
cranelift-jit = { version = "=0.134.2", optional = true }

[dev-dependencies]
bamts-runtime = { path = "../bamts-runtime", version = "0.1.2" }

[features]
default = []
aot = ["dep:cranelift-object"]
host-jit = ["dep:cranelift-jit", "dep:bamts-native"]

[lints]
workspace = true
