[package]
name = "bamts-cli"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "bamts"
path = "src/main.rs"

[dependencies]
bamts = { path = "../bamts", features = ["node-host"] }
bamts-compiler = { path = "../bamts-compiler" }
bamts-runtime = { path = "../bamts-runtime" }
bamts-codegen = { path = "../bamts-codegen", features = ["aot", "host-jit"] }
bamts-node = { path = "../bamts-node" }

[build-dependencies]
bamts-node = { path = "../bamts-node", features = ["aot-main", "script-compiler"] }

[lints]
workspace = true
