[package]
name = "bamts"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
aot = ["dep:bamts-codegen", "bamts-codegen/aot"]
host-jit = ["dep:bamts-codegen", "bamts-codegen/host-jit"]
node-host = ["dep:bamts-node", "bamts-node/node-host", "bamts-node/script-compiler"]

[dependencies]
bamts-bytecode = { path = "../bamts-bytecode" }
bamts-codegen = { path = "../bamts-codegen", optional = true }
bamts-compiler = { path = "../bamts-compiler" }
bamts-node = { path = "../bamts-node", optional = true }
bamts-runtime = { path = "../bamts-runtime" }

[lints]
workspace = true
