[package]
name = "bamts-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = true
license.workspace = true
repository.workspace = true
description = "TypeScript/JavaScript compiler frontend for BamTS"

[dependencies]
bamts-bytecode.workspace = true
bamts-cancel.workspace = true

[lints]
workspace = true
